### ISSUE TITLE
请教一个关于wechaty的问题

### ISSUE THREAD

**Issue by HelplessMan** [generalbao/paipiange-wechat-bot#1]
在wechaty的github里面找到了这里，然后想问问，这个协议目前用php 有什么办法来调用那。 看来好几个例子基本都是ts的。包括你的这个。 这要是不会写ts py go 岂不是很尴尬。。

**Comment by generalbao** [comment]
这也没办法 除非我们搞个php版本的

**Comment by HelplessMan** [comment]
貌似也只能这样了。。
